### ISSUE TITLE
Quitting Session causes "Exception ignored in"

### ISSUE THREAD

**Issue by frankmorgner** [LudovicRousseau/pyscard#131]
#### Your system information

* Operating system used: Ubuntu 20.04.4 LTS
* pyscard version: 1.9.9-2build1
* Python version: 3.8.2-0ubuntu2

#### Please describe your issue in as much detail as possible:
The following example uses the Session interface to connect to a card. While the script is running, unplug the reader. Consequently, when `session.close()` is called, this will throw a disconnection error (which is deliberately ignored).
```python
import smartcard
import time

readers = smartcard.System.listReaders()
readernum = 2
reader = readers[readernum]
session = smartcard.Session(reader)
print("remove %s", reader)
time.sleep(5)
try:
    session.close()
except:
    pass
```
[disconnect.txt](https://github.com/LudovicRousseau/pyscard/files/8640000/disconnect.txt)

However, some background process still has a connection and fails to report this exception properly when the script exits. That's why python reports this exception by printing it on the command line:
```
Exception ignored in: <function Session.__del__ at 0x7f8027d240d0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/smartcard/Session.py", line 85, in __del__
  File "/usr/lib/python3/dist-packages/smartcard/Session.py", line 91, in close
  File "/usr/lib/python3/dist-packages/smartcard/CardConnectionDecorator.py", line 58, in disconnect
  File "/usr/lib/python3/dist-packages/smartcard/pcsc/PCSCCardConnection.py", line 154, in disconnect
smartcard.Exceptions.CardConnectionException: Failed to disconnect: Invalid value given.
Exception ignored in: <function CardService.__del__ at 0x7f8027d04ee0>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/smartcard/CardService.py", line 52, in __del__
  File "/usr/lib/python3/dist-packages/smartcard/CardConnectionDecorator.py", line 58, in disconnect
  File "/usr/lib/python3/dist-packages/smartcard/pcsc/PCSCCardConnection.py", line 154, in disconnect
smartcard.Exceptions.CardConnectionException: Failed to disconnect: Invalid value given.
Exception ignored in: <function PCSCCardConnection.__del__ at 0x7f8027d8de50>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/smartcard/pcsc/PCSCCardConnection.py", line 88, in __del__
  File "/usr/lib/python3/dist-packages/smartcard/pcsc/PCSCCardConnection.py", line 154, in disconnect
smartcard.Exceptions.CardConnectionException: Failed to disconnect: Invalid value given.
```
Printing this backtrace should be avoided. See https://github.com/python/asyncio/issues/423 for a similar problem

#### Steps for reproducing this issue:

1. run `python disconnect.txt`
2. unplug the connected reader
3. when script exits, the ignored Exception can be observed

**Comment by LudovicRousseau** [comment]
Fixed.
Thanks
