### ISSUE TITLE
TypeError: CardRequestTimeoutException.__init__() got an unexpected keyword argument 'hresult'

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [LudovicRousseau/pyscard#165]
#### Your system information

* Operating system used: Windows 10 Build 19045
* pyscard version: 2.0.8
* Python version: 3.11.8

#### Please describe your issue in as much detail as possible:
_Describe what you _expected_ should happen._

I should have got a `CardRequestTimeoutException` when the card wasn't found.

_Describe what \*did\* happen._

I got a `TypeError` exception when the card wasn't found.

```
Traceback (most recent call last):
  File "…\test007.py", line 15, in <module>
    crd = req.waitforcard()
  File "…\.venv\Lib\site-packages\smartcard\CardRequest.py", line 68, in waitforcard
    return self.pcsccardrequest.waitforcard()
  File "…\.venv\Lib\site-packages\smartcard\pcsc\PCSCCardRequest.py", line 216, in waitforcard
    raise CardRequestTimeoutException(hresult=hresult)
TypeError: CardRequestTimeoutException.__init__() got an unexpected keyword argument 'hresult'
```

#### Steps for reproducing this issue:

1. Install pyscard
2. Don't insert a smartcard
3. Run this code:
   ```python
   import smartcard  # https://pypi.org/project/pyscard/
   import smartcard.CardRequest
   import smartcard.CardType
   
   class MyCardType(smartcard.CardType.CardType):
       @classmethod
       def matches(cls, atr, reader=None):
           return bytes(atr).startswith(cls.prefix)
       prefix = b'\x3b\xff\x13\x00\x00'
   
   req = smartcard.CardRequest.CardRequest(cardType=MyCardType)
   crd = req.waitforcard()
   con = crd.connection
   con.connect()
   print('ATR:', bytes(con.getATR()).hex())
   ```

**Comment by LudovicRousseau** [comment]
Thanks
