### ISSUE TITLE
pyscard 2.1.1 - Failed to get status change Cannot find a smart card reader. : Cannot find a smart card reader.  (0x8010002E)

### ISSUE THREAD

**Issue by deweydb** [LudovicRousseau/pyscard#207]
#### Your system information

* Operating system used: Windows 10 / Windows 11
* pyscard version: 2.1.1
* Python version: 3.12.4

#### Please describe your issue in as much detail as possible:
After upgrading from version 2.0.10 to 2.1.1 we have an issue with our Omnikey 5022 USB Reader we receive the following error:
```
Traceback (most recent call last):
  File "C:\Users\Adrian\AppData\Local\Programs\Python\Python312\Lib\site-packages\smartcard\CardMonitoring.py", line 165, in run
    currentcards = self.cardrequest.waitforcardevent()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Adrian\AppData\Local\Programs\Python\Python312\Lib\site-packages\smartcard\CardRequest.py", line 72, in waitforcardevent
    return self.pcsccardrequest.waitforcardevent()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Adrian\AppData\Local\Programs\Python\Python312\Lib\site-packages\smartcard\pcsc\PCSCCardRequest.py", line 291, in waitforcardevent
    readernames = self.getReaderNames()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Adrian\AppData\Local\Programs\Python\Python312\Lib\site-packages\smartcard\pcsc\PCSCCardRequest.py", line 99, in getReaderNames
    raise ListReadersException(hresult)
smartcard.Exceptions.ListReadersException: Failed to list readers: The action was cancelled by an SCardCancel request.  (0x80100002)
Traceback (most recent call last):
  File "C:\Users\Adrian\AppData\Local\Programs\Python\Python312\Lib\site-packages\smartcard\CardMonitoring.py", line 165, in run
    currentcards = self.cardrequest.waitforcardevent()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Adrian\AppData\Local\Programs\Python\Python312\Lib\site-packages\smartcard\CardRequest.py", line 72, in waitforcardevent
    return self.pcsccardrequest.waitforcardevent()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Adrian\AppData\Local\Programs\Python\Python312\Lib\site-packages\smartcard\pcsc\PCSCCardRequest.py", line 322, in waitforcardevent
    raise CardRequestException(
smartcard.Exceptions.CardRequestException: Failed to get status change Cannot find a smart card reader. : Cannot find a smart card reader.  (0x8010002E)
```

In an effort to try to understand what is going wrong i printed out hresult right before this exception is called and got:
-2146435070

Reverting to pyscard 2.0.10 seems to resolve the issue. Please let me know if I can assist in any further tests or debugging of the issue.

**Comment by LudovicRousseau** [comment]
can you provide a sample code to reproduce the issue?

**Comment by LudovicRousseau** [comment]
I can't reproduce the problem with the current/unreleased code.
I modified a bit your code to add some debug and make it worl with any card.
```patch
$ diff -u bug_orig.py bug2.py
--- bug_orig.py 2024-10-09 11:49:54.076068500 +0200
+++ bug2.py     2024-10-09 11:53:37.586248300 +0200
@@ -1,13 +1,11 @@
 from smartcard.CardMonitoring import CardObserver, CardMonitor
 from smartcard.util import toBytes, toHexString
-from smartcard.CardType import ATRCardType
+from smartcard.CardType import AnyCardType
 from smartcard.CardRequest import CardRequest
 from smartcard.Exceptions import CardRequestTimeoutException, CardConnectionException
 from functools import partial
 import threading

-DEFAULT_WRITER = print
-DEFAULT_CARD_ATR = "3B 81 80 01 80 80"
 DEFAULT_TIMEOUT = 5.0

 class Response:
@@ -28,6 +26,7 @@
         return toHexString(self.data, *args, **kwargs)

 def dispatch(command: list, service) -> Response:
+    print("dispatch")
     raw_response = service.connection.transmit(command)
     response = Response(raw_response)
     return response
@@ -39,7 +38,7 @@
         self.auth = auth
         self.threading_event = threading_event
         self.send = None
-        card_type = ATRCardType(toBytes(DEFAULT_CARD_ATR))
+        card_type = AnyCardType
         card_request = CardRequest(timeout=DEFAULT_TIMEOUT, cardType=card_type)
         self.result = None

@@ -50,6 +49,7 @@
             return None

     def update(self, _, handlers):
+        print("update:", handlers)
         added, _ = handlers
         if added:
             try:
@@ -63,6 +63,7 @@
                 return None

     def pre_auth(self) -> list | None:
+        print("pre_auth")
         if not self.auth:
             return None
         try:
```

If I start the program with a card already inserted I immediately get:
```
update: ([], [])
```
If I start the program with no card inserted and I insert a card I get:
```
update: ([3B 6F 00 00 80 5A 28 13 02 10 12 2B 75 11 8E 47 82 90 00 / Alcor Micro USB Smart Card Reader 0], [])
pre_auth
```
If I start the program with no card inserted and I just wait I get, after 5 seconds:
```
update: ([], [])
```
I guess that is the expected behaviour.

Can you install the current code from git and try on your side?

**Comment by LudovicRousseau** [comment]
With PySCard 2.1.1 I reproduce your problem.
I also see that if I start the test program with a card already inserted I get
```
update: ([3B 6F 00 00 80 5A 28 13 02 10 12 2B 75 11 8E 47 82 90 00 / Alcor Micro USB Smart Card Reader 0], [])
pre_auth
```
Instead of an empty `added` variable. I will fix that.

**Comment by LudovicRousseau** [comment]
I fixed the previous issue.
For me everything works fine with the current code in git.

Please test on your side and confirm it is OK for you.

**Comment by deweydb** [comment]
Thank you!!
Latest version from git does resolve this original issue in this thread, however it seems to introduce a different issue in our application further down the line when doing the initial handshaking with the cards.

The following code is working in 2.0.10 but in the latest version from git we are getting a response with a status code of:
91 1C: Command code not supported

This is happening at approximately line 246 of the following sample code:

```
from smartcard.CardMonitoring import CardObserver, CardMonitor
from smartcard.util import toBytes, toHexString
from smartcard.CardType import ATRCardType
from smartcard.CardRequest import CardRequest
from smartcard.Exceptions import CardRequestTimeoutException, CardConnectionException
from functools import partial
import threading

DEFAULT_WRITER = print
DEFAULT_CARD_ATR = "3B 81 80 01 80 80"
DEFAULT_TIMEOUT = 5.0

class Response:
    def __init__(self, raw_response: list):
        self.data, sw1, sw2 = raw_response
        self.status = sw1, sw2

    def is_successful(self):
        return self.status in [(0x91, 0x00), (0x90, 0x00), (0x91, 0xAF)]

    def to_bytes(self):
        return bytearray(self.data)

    def to_string(self):
        return self.to_bytes().decode("utf-8")

    def to_hex_string(self, *args, **kwargs):
        return toHexString(self.data, *args, **kwargs)

def dispatch(command: list, service) -> Response:
    raw_response = service.connection.transmit(command)
    response = Response(raw_response)
    return response


class Observer(CardObserver):
    def __init__(self, callback=None, auth: dict | None = None, threading_event=None):
        self.callback = callback
        self.auth = auth
        self.threading_event = threading_event
        self.send = None
        card_type = ATRCardType(toBytes(DEFAULT_CARD_ATR))
        card_request = CardRequest(timeout=DEFAULT_TIMEOUT, cardType=card_type)
        self.result = None

        try:
            self.service = card_request.waitforcard()
            self.service.connection.connect()
        except (CardRequestTimeoutException, CardConnectionException) as e:
            return None

    def update(self, _, handlers):
        added, _ = handlers
        if added:
            try:
                self.send = partial(dispatch, service=self.service)
                session_key = self.pre_auth()
                self.result = self.callback(
                    send=self.send, session_key=session_key)
                self.service.connection.disconnect()
                self.threading_event(self.result)
            except CardConnectionException as e:
                return None

    def pre_auth(self) -> list | None:
        if not self.auth:
            return None
        try:
            print("placeholder...")
            return "redacted"
        except Exception as e:
            print(e)

class Omnikey(CardMonitor):
    def __init__(self, config=None):
        super().__init__()
        self.config = config
        self.scan_event = threading.Event()

    def threading_event_callback(self, result):
        self.observer_result = result
        self.scan_event.set()

    def basic(self, *args, **kwargs):
        def decorator(func):
            def wrapper():
                callback = partial(func, *args, **kwargs)
                observer = Observer(
                    callback=callback, threading_event=self.threading_event_callback
                )
                self.addObserver(observer)
                self.deleteObserver(observer)
                return observer.result

            return wrapper

        return decorator

    def authenticate(self, *args, **kwargs):
        def decorator(func):
            def wrapper():
                callback = partial(func, *args, **kwargs)
                observer = Observer(
                    callback=callback,
                    auth=self.config,
                    threading_event=self.threading_event_callback,
                )
                self.addObserver(observer)
                self.deleteObserver(observer)
                return observer.result

            return wrapper

        return decorator

omnikey = Omnikey()

def command_get_version() -> list:
    """
    60 : Get Version
    This gets the card version details, including manufacturing info and its uid.
    """
    apdu = [0x90, 0x60, 0x00, 0x00]
    le = 0x00
    apdu.append(le)
    return apdu

def command_additional_frame(data: list = None) -> list:
    """
    AF: Additional Frame
    This sends data pertaining to a previous command as an additional frame.
    Must be sent in a response to a status code of AF.
    """
    apdu = [0x90, 0xAF, 0x00, 0x00]

    if data:
        lc = len(data)
        apdu.append(lc)
        apdu += data

    le = 0x00
    apdu.append(le)
    return apdu

from Crypto.Cipher import AES, DES
import numpy as np
from collections import deque

class Auth:
    engines = {"AES": (AES, 16), "DES": (DES, 8)}

    def __init__(self, key, encryption: str):
        self.engine, self.index = self.engines[encryption]

        self.key = key
        self.iv = None
        self.cipher = None
        self.random_a = None
        self.random_b = None
        self.session_key = None

    def authenticate(self, ciphertext: list) -> list:
        ciphertext = bytearray(ciphertext)
        self.iv = bytearray([0x00] * self.index)
        self.cipher = self.engine.new(self.key, self.engine.MODE_CBC, iv=self.iv)
        self.random_b = self.cipher.decrypt(ciphertext)
        self.random_a = list(np.random.randint(0, 255, self.index))
        random_b_prime = deque(list(self.random_b))
        random_b_prime.rotate(-1)
        random_b_prime = list(random_b_prime)
        concatenated = bytearray(self.random_a + random_b_prime)
        self.iv = ciphertext
        cipher = self.engine.new(self.key, self.engine.MODE_CBC, iv=self.iv)
        encrypted_concatenated = cipher.encrypt(concatenated)
        self.iv = encrypted_concatenated[-self.index :]
        result = list(encrypted_concatenated)
        return result

    def get_session_key(self, ciphertext: list) -> None:
        cipher = self.engine.new(self.key, self.engine.MODE_CBC, iv=self.iv)
        result = cipher.decrypt(bytearray(ciphertext))
        check = deque(self.random_a)
        check.rotate(-1)
        if list(check) == list(result):
            if self.engine == AES:
                part_1 = list(self.random_a[:4]) + list(self.random_b[:4])
                part_2 = list(self.random_a[-4:]) + list(self.random_b[-4:])
                self.session_key = part_1 + part_2
            if self.engine == DES:
                self.session_key = list(self.random_a[:4]) + list(self.random_b[:4])
        return self.session_key

def command_aes_auth(key_id: list) -> list:
    """
    AA: Authenticate (AES)
    This allows you to authenticate for a specified key number using AES.
    If the key is not AES you get an AE error back. The key number is the key in the current application.
    If top level (AID 0) selected or no application selected yet then this is the master key for the card (key 0).
    """
    apdu = [0x90, 0xAA, 0x00, 0x00]
    lc = [0x01]
    apdu += lc
    apdu += key_id
    le = [0x00]
    apdu += le
    return apdu

@omnikey.basic()
def create_card(**kwargs):
    send = kwargs.get("send")

    send(command_get_version())
    send(command_additional_frame())
    response = send(command_additional_frame())
    uid = response.data[:7]

    SECRET_PICC_MASTER_KEY = [...redacted...]

    key = bytearray(SECRET_PICC_MASTER_KEY)
    auth = Auth(key, "AES")
    print('get challenge ' + ' '.join(f'{x:02x}' for x in command_aes_auth([0x00])))
    response = send(command_aes_auth([0x00]))

    if not response.is_successful():
        key = bytearray(DEFAULT_DES_KEY)
        auth = Auth(key, "DES")
        response = send(command_des_auth([0x00]))
        if not response.is_successful():
            print("could not perform initial AES or DES auth, response code:" + ' '.join(f'{x:02x}' for x in response.status))

    challenge = response.data
    print('challenge ' + ' '.join(f'{x:02x}' for x in challenge))
    submission = auth.authenticate(challenge)
    print('submission ' + ' '.join(f'{x:02x}' for x in submission))
    print('sub framed ' + ' '.join(f'{x:02x}' for x in command_additional_frame(submission)))
    response = send(command_additional_frame(submission))
    print('response ' + ' '.join(f'{x:02x}' for x in response.data))

    if not response.is_successful():
        print("could not perform initial AES or DES auth, response code:" + ' '.join(f'{x:02x}' for x in response.status))

create_card()
```

**Comment by LudovicRousseau** [comment]
Your code has only 242 lines.
I don't know where is the line 246 that has the problem.

It will be very difficult for me to debug without your card.

I suggest you to have a look at the APDUs exchanged in your sample code between PySCard 2.0.10 and the git version.

**Comment by LudovicRousseau** [comment]
No feedback.
If you found another problem in PySCard please open a new ticket with all the details.
Thanks
